repos:
  - repo: local
    hooks:
      - id: no-license-comment
        name: Forbid LICENSE comments
        language: pygrep
        types: [python]
        entry: '^# .* LICENSE '
      - id: bad-import-000
        name: Incompatible import with old versions in `0.0.0` scripts
        language: pygrep
        entry: '(from|import) odoo.upgrade\b'
        files: '^migrations/\w+/0.0.0/.*\.py$'

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-implicit-str-concat
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-symlinks
    - id: debug-statements
