repos:
  - repo: local
    hooks:
      - id: no-license-comment
        name: Forbid LICENSE comments
        language: pygrep
        types: [python]
        entry: '^# .* LICENSE '
      - id: bad-import-000
        name: Incompatible import with old versions in `0.0.0` scripts
        language: pygrep
        entry: '(from|import) odoo.upgrade\b'
        files: '^migrations/\w+/0.0.0/.*\.py$'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff-format
      - id: ruff
        name: ruff-required
        args:
          - --ignore=FIX,PLR6301,PLR2004,ERA
          - --fix
          - --exit-non-zero-on-fix
      - id: ruff
        name: ruff-optional
        verbose: true
        args:
          - --select=FIX,PLR6301,PLR2004,ERA
          - --no-fix
          - --exit-zero

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-xml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-symlinks
    - id: debug-statements
