name: custom_util

on:
  pull_request:
    branches:
      - master
jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pre-commit install

      - name: Run pre-commit
        run: |
          git switch -C ${{ github.base_ref }} --track origin/${{ github.base_ref }}
          git switch -C ${{ github.head_ref }} --track origin/${{ github.head_ref }}
          pre-commit run --from-ref ${{ github.base_ref }} --to-ref ${{ github.head_ref }}
